### PR TITLE
update embed (1.420.69.idk)

### PR DESCRIPTION
**Pull request by PRinCeThePro69**
Update add field to embed in '_achievements'

### CODE REVIEW

**Review by Deveroonie — CHANGES_REQUESTED** [review]
Can you add it so everything has it's own field as that looks messy.

**Comment by PRinCeThePro69** [comment]
aight

**Review by Deveroonie — APPROVED** [review]
Thanks for your contribution!

**Comment by PRinCeThePro69** [comment]
ty

**Pull request merged**
